### ISSUE TITLE
PyPi package update

### ISSUE THREAD

**Issue by andreax79** [python-otr/pure-python-otr#74]
The PyPi package  https://pypi.python.org/pypi/python-potr 1.0.1 is quite old (2014-10-16).
Please consider releasing a new version.

**Comment by koolfy** [comment]
Yes this has been in my mind for quite some time.
I wanted to finish the next release before distributing a new packaged version, but as I'm not moving very fast on that front... it's probably better to release whatever stable branch we have now and have another release later, instead of waiting some more.

**Comment by koolfy** [comment]
PyPi package has been bumped with the 1.0.2 release.
I signed the release with my pgp key, but apparently pip will never care, so that's that :(

You can find the signature there: https://files.pythonhosted.org/packages/8e/58/bcbd8f223512d733992fcc0793170ffe20af2cd8da50e73c6f14e66d4e16/python-potr-1.0.2.tar.gz.asc
